description: Ultralytics YOLO26n model trained on /home/j/vision_marker/ifof/merged/data.yaml
author: Ultralytics
date: '2026-09-05T11:02:28.249945'
version: 8.4.101
license: AGPL-3.0 License (https://ultralytics.com/license)
docs: https://docs.ultralytics.com
stride: 32
task: detect
head: Detect
batch: 1
imgsz:
- 320
- 320
names:
  0: A
  1: E
  2: Enemy
  3: Heart
  4: K
  5: M
  6: O
  7: R
  8: ROKA
  9: Y
  10: friend
args:
  data: merged/data.yaml
  batch: 1
  fraction: 1.0
  quantize: 8
  dynamic: false
  nms: false
channels: 3
end2end: true
