<?xml version="1.0"?>
<package format="3">
  <name>changer_manipulator_bringup</name>
  <version>0.1.0</version>
  <description>External controller bringup namespace for changer_manipulator.</description>
  <maintainer email="shu@example.invalid">shu</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>changer_manipulator_moveit_config</exec_depend>
  <exec_depend>tool_manipulator_description</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
